env:
  - LUA='Lua 5.1'
  - LUA='Lua 5.2'
  - LUA='Lua 5.3'
  - LUA='LuaJIT 2.0'

dependencies:
  pre:
    - bin/lua_install.sh
    - sudo apt-get install libphysfs-dev
    - sudo luarocks install busted
    - sudo luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu/
    - sudo luarocks install luacov
test:
  override:
    - mkdir $CIRCLE_TEST_REPORTS/busted
    - busted -c -o junit spec > $CIRCLE_TEST_REPORTS/busted/dilemma.xml
  post:
    - luacov -c=spec/.luacov
    - bash <(curl -s https://codecov.io/bash)
